# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-src/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 525)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 525))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textOutput.setGeometry(QtCore.QRect(20, 50, 511, 311))
        self.textOutput.setObjectName("textOutput")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 521, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputURL = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputURL.setObjectName("inputURL")
        self.horizontalLayout.addWidget(self.inputURL)
        self.btnCrawl = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCrawl.setObjectName("btnCrawl")
        self.horizontalLayout.addWidget(self.btnCrawl)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputURL.setText(_translate("MainWindow", "https://www.stretchtheirlegs.co.uk/"))
        self.btnCrawl.setText(_translate("MainWindow", "Crawl"))
