# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-src/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 495)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 525))
        MainWindow.setWindowOpacity(-4.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputURL = QtWidgets.QLineEdit(self.centralwidget)
        self.inputURL.setObjectName("inputURL")
        self.horizontalLayout.addWidget(self.inputURL)
        self.btnCrawl = QtWidgets.QPushButton(self.centralwidget)
        self.btnCrawl.setObjectName("btnCrawl")
        self.horizontalLayout.addWidget(self.btnCrawl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textOutput.setObjectName("textOutput")
        self.verticalLayout.addWidget(self.textOutput)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SEO Tool"))
        self.inputURL.setText(_translate("MainWindow", "https://www.stretchtheirlegs.co.uk/"))
        self.btnCrawl.setText(_translate("MainWindow", "Crawl"))
